# daemon off;
# ↑↑↑↑↑↑↑↑↑↑ここに書いておけば、CMD ["nginx"] だけで起動してもコンテナは終了しませんが
# このファイルの中に daemon off; を書かない理由は、主に以下の 2 点です。

# 設定ファイルの再利用性:
# 同じ nginx.conf を、Docker ではない普通の Linux サーバー（仮想マシンなど）でも使いたい場合があります。
# その場合、設定ファイルに daemon off; がハードコードされていると、普通のサーバーで systemctl start nginx した時にバックグラウンドに回らず、ターミナルが占有されて不便です。

# Docker の慣習:
# 「このコンテナはフォアグラウンドで動かす必要がある」というのは、**アプリケーションの設定（Nginxの挙動）というよりは、インフラ側の要請（Dockerの仕様）**です。
# そのため、インフラ側の設定である Dockerfile や docker run 側で制御するのがマナーだと考えるエンジニアが多いのです。
#
# 一次資料（ブロック構造の入口）: https://nginx.org/en/docs/beginners_guide.html

# 接続処理
# https://nginx.org/en/docs/ngx_core_module.html#events
events {

}

# HTTP全体
http {
	server {
		listen 80;								# HTTP(暗号化なし)で来たら
		server_name torinoue.42.fr;
		return 301 https://$host$request_uri;	# HTTPSに永久リダイレクト
	}

	# TLS 終端: https://nginx.org/en/docs/http/ngx_http_ssl_module.html
	server {
		listen 443 ssl;
		server_name torinoue.42.fr;
		ssl_certificate /etc/nginx/ssl/torinoue_server.crt;
		ssl_certificate_key /etc/nginx/ssl/torinoue_server.key;
		ssl_protocols TLSv1.2 TLSv1.3;

		root /var/www/html;
		index index.php index.html;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ .*\.(jpg|jpeg|gif|png|css|js|ico|woff)$ {
			expires 42m;
		}

		# FastCGI: https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html
		location ~ \.php$ {
			fastcgi_pass wordpress:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			include fastcgi_params;
		}
	}
}

