# version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    secrets:
      - db_root_password
      - db_password
    # environment:
    #   MARIADB_ROOT_PASSWORD: run/secrets/db_root_password
    #   MARIADB_PASSWORD: run/secrets/db_password
      # MARIADB_DATABASE: wordpress
      # MARIADB_USER: wpuser
    networks:
      - torinoue_network
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    # dns: 8.8.8.8
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    secrets:
      - wp_admin_password
      - db_password
    # environment:
      # - DOMAIN_NAME=${YOUR_LEARNER_USERNAME}.42.fr
      # - WP_ADMIN_USER=boss42
      # WP_ADMIN_PASSWORD: run/secrets/wp_admin_password
      
      # - WP_ADMIN_EMAIL=admin@example.com
      # - WP_USER=wpeditor  ←secretsへ入れない。プラグインの変更などの権限はないので。
      # - WP_USER_EMAIL=editor@example.com
      # - WP_USER_PASSWORD=wpeditorpass
      # - MARIADB_DATABASE=wordpress
      # - MARIADB_USER=wpuser
      # MARIADB_PASSWORD: run/secrets/db_password
    networks:
      - torinoue_network

  nginx:
    depends_on:
      # - mariadb
      - wordpress
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    networks:
      - torinoue_network

volumes:
  mariadb_data:
    driver: local # ホストOS（Linuxカーネル）のmount機能を直接利用する設定
    driver_opts:
      # 1. 【実体の特定】ホストOS上の、Docker管理外にある物理ディレクトリをソースに指定 
      # device: /home/${YOUR_LEARNER_USERNAME}/data/mariadb
      device: /home/torinoue/data/mariadb

      # 2. 【接続方法の指定】ホストのmount(8)にある「--bind」オプションを使用し、
      #    既存のディレクトリ構造をそのままコンテナにマッピング（再配置）する
      o: bind

      # 3. 【型定義のスキップ】
      #    device（ホスト側のパス）は既に特定のファイルシステム（ext4等）として存在している。
      #    ここで別の型（tmpfsなど）を強制指定すると、マウント時のドライバ不適合によりエラーとなる。
      #    そのため、既存のファイルシステムの性質をそのまま引き継ぐ「none」を指定する。
      type: none

  wordpress_data:
    driver: local
    driver_opts:
      # device: /home/${YOUR_LEARNER_USERNAME}/data/wordpress
      device: /home/torinoue/data/wordpress
      o: bind
      type: none

networks:
  torinoue_network:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
