[www]
user = nobody
group = nobody

listen = 9000

pm = dynamic
# 下記のパラメーターはデフォルト値と同じだが、結合テストで変更して最小値を探る
# 確認用Spike:
# docker run --rm --interactive --tty alpine:3.21 sh -c "
#   apk add --no-cache php83-fpm &&
#   cat /etc/php83/php-fpm.d/www.conf | grep -E '^pm\.'
# "

pm.max_children = 5
# 最大子プロセス数（同時リクエスト処理数の上限）
pm.start_servers = 2
# 起動時のプロセス数
pm.min_spare_servers = 1
# アイドル状態で維持する最小プロセス数
pm.max_spare_servers = 3
# アイドル状態で維持する最大プロセス数

# 下記を満たす必要がある
# pm.min_spare_servers ≤ pm.start_servers ≤ pm.max_spare_servers ≤ pm.max_children