# Vagrant.configure("2") do |config|
# #  config.vm.box = "bento/ubuntu-22.04-arm64"
#   config.vm.box = "bento/ubuntu-22.04"
#   config.vm.network "forwarded_port", guest: 443, host: 443, host_ip: "127.0.0.1"

#   config.vm.synced_folder "../../", "/vagrant"

#   config.vm.provider "vmware_fusion" do |vf|
#     vf.memory = "4096"
#     vf.cpus = 2
#   end

#   config.vm.provision "shell", path: "init.sh", privileged: false
# end



# Vagrant.configure("2") do |config|
#   config.vm.box = "bento/ubuntu-22.04"

#   # 切り分け中は 443 を外す（privileged port要因を除外）
#   config.vm.network "forwarded_port", guest: 443, host: 443, host_ip: "127.0.0.1"

#   config.vm.synced_folder "../../", "/vagrant"

#   config.vm.provider "virtualbox" do |vb|
#     vb.memory = "1024"
#     vb.cpus = 2
#     # vb.customize ["modifyvm", :id, "--paravirtprovider", "minimal"]
#     # vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
#     # vb.customize ["modifyvm", :id, "--audio", "none"]
#   end

#   config.vm.provision "shell", path: "init.sh", privileged: false
# end



# Vagrant.configure("2") do |config|
#   config.vm.box = "bento/ubuntu-22.04"
  
#   # 共有フォルダ設定（一旦カレントディレクトリでテスト）
#   config.vm.synced_folder ".", "/vagrant"

#   config.vm.provider "virtualbox" do |vb|
#     vb.memory = "2048"
#     vb.cpus = 2
#     # 第12世代以降で有効な場合があるおまじない
#     vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
#     # 第12世代以降のCPUでのクラッシュ回避用（Core i7-14700など）
#     vb.customize ["modifyvm", :id, "--cpu-profile", "host"]



    
#   end
# end


# ENV['LD_LIBRARY_PATH'] = nil

# Vagrant.configure("2") do |config|
#   config.vm.box = "bento/ubuntu-22.04"
#   config.vm.synced_folder ".", "/vagrant"

#   config.vm.provider "virtualbox" do |vb|
#     vb.memory = "2048"
#     vb.cpus = 2

#     # --- 第14世代 CPU クラッシュ対策（ここが重要！） ---
#     # CPUの種類を host に設定して、ハイブリッドコアによる誤認を防ぐ
#     # vb.customize ["modifyvm", :id, "--cpu-profile", "host"]
    
#     # 物理的なハードウェア仮想化支援を強制（環境によって必要）
#     # vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    
# # 命令セットを「Core2 Quad」レベルまで落として古いVBoxに誤認させる（最終手段）
#     vb.customize ["modifyvm", :id, "--cpu-profile", "Intel Core2 Quad Q6600"]


#     # オーディオをオフにして安定させる
#     vb.customize ["modifyvm", :id, "--audio", "none"]
#     # -----------------------------------------------
#   end
# end


# Vagrantが勝手にセットするライブラリパスを完全に無効化する

ENV['LD_LIBRARY_PATH'] = nil

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder "../../", "/vagrant"
  config.vm.network "forwarded_port", guest: 443, host: 4443

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

  config.vm.provision "shell", path: "init.sh", privileged: false
end