Vagrant.configure("2") do |config|
#  config.vm.box = "bento/ubuntu-22.04-arm64"
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "forwarded_port", guest: 443, host: 443, host_ip: "127.0.0.1"

  config.vm.synced_folder "../../", "/vagrant"

  config.vm.provider "vmware_fusion" do |vf|
    vf.memory = "4096"
    vf.cpus = 2
  end

  config.vm.provision "shell", path: "init.sh", privileged: false
end
